### ISSUE TITLE
Smooth video generation

### ISSUE THREAD

**Issue by G-Prajwal** [Make-A-Protagonist/Make-A-Protagonist#19]
The generated video is not temporally consistent, has flickering colours and changing backgrounds. Need suggestions  to ensure temporal consistency and style consistency for all the frames of the video...

**Comment by HeliosZhao** [comment]
Hi, reducing the influence of ControlNet might be one way to improve temporal consistency. 

Since the estimated control signals are not quite accurate and temporally consistent, especially the depth, the ControlNet features might introduce temporal inconsistency and artifacts to the background. However, control signals help to ensure the motion. Therefore, it is a trade-off between motion accuracy and background consistency.
